export const ADD_CHILD = "ADD_CHILD";
export const REMOVE_NODE = "REMOVE_NODE";
export const REORDER_NODES = "REORDER_NODES";
export const MOVE_NODE = "MOVE_NODE";
export const RESIZE_NODE = "RESIZE_NODE";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const UPDATE_LAYOUT = "UPDATE_LAYOUT";
export const SET_CONTENT = "SET_CONTENT";
export const SET_MAP_FILE = "SET_MAP_FILE";
export const CHANGE_SAVING_STATUS = "CHANGE_SAVING_STATUS";
export const UPDATE_UPLOADS_IN_PROGRESS_COUNT =
  "UPDATE_UPLOADS_IN_PROGRESS_COUNT";
export const UPDATE_UPLOAD_STATUS = "UPDATE_UPLOAD_STATUS";
export const DELETE_UPLOAD_STATUS = "DELETE_UPLOAD_STATUS";
export const UPDATE_NEXT_PAGE_TOKEN = "UPDATE_NEXT_PAGE_TOKEN";
export const ADD_TO_MAP_FILE_LIST = "ADD_TO_MAP_FILE_LIST";
export const DELETE_FROM_MAP_FILE_LIST = "DELETE_FROM_MAP_FILE_LIST";
