export const ADD_CHILD = "ADD_CHILD";
export const REMOVE_NODE = "REMOVE_NODE";
export const REORDER_NODES = "REORDER_NODES";
export const MOVE_NODE = "MOVE_NODE";
export const RESIZE_NODE = "RESIZE_NODE";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const UPDATE_LAYOUT = "UPDATE_LAYOUT";
export const SET_CONTENT = "SET_CONTENT";
export const CHANGE_SAVING_STATUS = "CHANGE_SAVING_STATUS";
export const UPDATE_UPLOADS_IN_PROGRESS_COUNT =
  "UPDATE_UPLOADS_IN_PROGRESS_COUNT";
export const UPDATE_UPLOAD_STATUS = "UPDATE_UPLOAD_STATUS";
